# Generated by Django 5.1.4 on 2024-12-07 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_maintenancestandard_maintenance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancestandard',
            name='interval_days',
        ),
        migrations.RemoveField(
            model_name='maintenancestandard',
            name='maintenance_type',
        ),
        migrations.AddField(
            model_name='maintenancestandard',
            name='interval_kr',
            field=models.IntegerField(default=300, help_text='Интервал для КР (в днях)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancestandard',
            name='interval_to',
            field=models.IntegerField(default=15, help_text='Интервал для ТО (в днях)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancestandard',
            name='interval_tr',
            field=models.IntegerField(default=60, help_text='Интервал для ТР (в днях)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancestandard',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_standard', to='equipment.equipment'),
        ),
    ]
