# Generated by Django 5.0.4 on 2024-12-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipmenttype_equipment_is_displayed_and_more'),
    ]

    operations = [ 
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-installation_date'], 'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='Изображение'),
        ),
    ]
