# Generated by Django 5.1.4 on 2024-12-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_maintenancestandard_interval_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='equipment.equipment'),
        ),
    ]
