# Generated by Django 5.0.4 on 2024-12-25 15:45

from django.db import migrations
from django.utils.text import slugify

def fill_unique_slugs(apps, schema_editor):
    EquipmentType = apps.get_model('equipment', 'EquipmentType')
    db_alias = schema_editor.connection.alias
    for item in EquipmentType.objects.using(db_alias).all():
        base_slug = slugify(item.name)
        slug = base_slug
        counter = 1
        while EquipmentType.objects.using(db_alias).filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        item.slug = slug 
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmenttype_slug_alter_equipment_equipment_type_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_unique_slugs),
    ]