# Generated by Django 5.0.4 on 2024-12-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_fill_equipmenttype_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
 