# Generated by Django 5.0.4 on 2024-12-27 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_equipmenttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetype',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', max_length=255, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='slug',
            field=models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
