# Generated by Django 5.0.4 on 2024-12-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_maintenancetype_slug_alter_equipmenttype_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='maintenance_types',
        ),
    ]
