# Generated by Django 5.0.4 on 2024-12-27 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_remove_equipment_maintenance_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='maintenance_type',
            field=models.CharField(choices=[('to', 'ТО'), ('tr', 'ТР'), ('kr', 'КР')], max_length=2, verbose_name='Тип обслуживания'),
        ),
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_periodicity', models.IntegerField(verbose_name='Периодичность ТО (дни)')),
                ('tr_periodicity', models.IntegerField(blank=True, null=True, verbose_name='Периодичность ТР (дни)')),
                ('kr_periodicity', models.IntegerField(blank=True, null=True, verbose_name='Периодичность КР (дни)')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Периодичность обслуживания оборудования',
                'verbose_name_plural': 'Периодичности обслуживания оборудования',
            },
        ),
        migrations.DeleteModel(
            name='EquipmentMaintenanceType',
        ),
        migrations.DeleteModel(
            name='MaintenanceType',
        ),
    ]
